name: Art ğŸ’™ğŸ³ï¸â€ğŸŒˆ
tagline: Ambulances & Programming
description: Part-time programmer & ambulance 999 operator from the UK
url: https://words.artofcode.co.uk
baseurl: ''

permalink: /:slug/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


social:
  twitter: https://twitter.com/_ArtOfCode
  github: https://github.com/ArtOfCode-
  stack-overflow: https://stackoverflow.com/users/3160466

cat_classes:
  '999': bc-green-darkest
  dev: bc-purple-darkest